### ISSUE TITLE
Add support for pg_catelog tables to enable Alchemic

### ISSUE THREAD

**Issue by zhenthebuilder** [GoogleCloudPlatform/pgadapter#1129]
pgadapter's [limitation](https://github.com/GoogleCloudPlatform/pgadapter/blob/postgresql-dialect/samples/python/sqlalchemy2-sample/README.md#limitations) on not supporting all pg_catalog tables blocks using Spanner + Postgres + Alchemic. Full trace stack [here](https://elmah.io/tools/stack-trace-formatter/5aa429cb51d645c981f2401a62b3ba6a/). This makes it hard for anyone try to use Spanner with postgres to have a proper python ORM + schema migration solution.

I wonder how hard it is to support pg_catelog tables (here specifically pg_namespace and pg_class) in pgadapter? Or if there's any alternative suggested?

**Comment by olavloite** [comment]
[`pg_namespace`](https://github.com/GoogleCloudPlatform/pgadapter/blob/7bb4af0fee07c8e38aac2ad9d58a41cbf70e9b69/src/main/java/com/google/cloud/spanner/pgadapter/statements/PgCatalog.java#L296) and [`pg_class`](https://github.com/GoogleCloudPlatform/pgadapter/blob/7bb4af0fee07c8e38aac2ad9d58a41cbf70e9b69/src/main/java/com/google/cloud/spanner/pgadapter/statements/PgCatalog.java#L432) are actually emulated and hence supported in PGAdapter. However, the specific query uses a join condition that PGAdapter does not recognize: `ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace`

The fully qualified table name in the join clause is not detected by PGAdapter, and the query therefore fails. We can take a look at fixing that.

That being said, there is no guarantee that `Alembic` won't use other pg_catalog tables that are not supported. The problem with many schema migration solutions is that they use a wide variety of pg_catalog tables and functions in generated queries, and it is enough to hit just one unsupported table or function for the tool not to work.

**Comment by zhenthebuilder** [comment]
Thanks for the response, Alembic or other database migration tool are critical on using the Spanner + Postgres in production. Given Alembic is not easy to support, what's the suggested migration tool for Spanner + Postgres?

**Comment by olavloite** [comment]
> Thanks for the response, Alembic or other database migration tool are critical on using the Spanner + Postgres in production. Given Alembic is not easy to support, what's the suggested migration tool for Spanner + Postgres?

We have tested and verified support for [Liquibase](https://github.com/GoogleCloudPlatform/pgadapter/blob/postgresql-dialect/docs/liquibase.md) with some limitations.

More in general: Tools that do not try to automatically generate schema statements and/or automatically try to compare the current schema with code will work better. The problem with very many of these tools is that they use a wide variety of `pg_catalog` tables and functions. Adding workarounds for each of them is infeasible. Tools that expect you to manually craft the DDL statements that you want to execute during a version upgrade will have a much bigger chance of working.
