### ISSUE TITLE
Arrays encoded using the binary protocol are always sent with lower bound 0

### ISSUE THREAD

**Issue by olavloite** [GoogleCloudPlatform/pgadapter#1259]
Arrays that are encoded using the binary format are always sent with lower bound zero:

https://github.com/GoogleCloudPlatform/pgadapter/blob/b55f92439036d319b35972ff668a954a8fc4a335/src/main/java/com/google/cloud/spanner/pgadapter/parsers/ArrayParser.java#L323

The default in PostgreSQL is to use 1 as the lower bound of an array.

**Comment by jackpertschuk** [comment]
any update on this?
