### ISSUE TITLE
Invalid JDBC connection

### ISSUE THREAD

**Issue by ccfelius** [GoogleCloudPlatform/pgadapter#51]
Hi, 

I keep running into this issue while executing the jar file:

```
SEVERE: Something went wrong in establishing a Spanner connection: Invalid JDBC connection. 
Make sure credentials are valid.
```

What does this error mean? Do I  need the preview for this to work?

**Comment by olavloite** [comment]
It means that the connection from PGAdapter to your Cloud Spanner database (created with PostgreSQL dialect) failed. This can have many reasons:
1. If you built the jar from the `postgresql-dialect` branch (the default branch for this repository), then PGAdapter can only be used to connect to Cloud Spanner databases that have been created with the PostgreSQL dialect. You need access to the preview to do that.
2. It could be that your connection details or credentials are invalid.

Do you have any more information about the database that you are trying to connect to, and exactly which jar you are using?

**Comment by ccfelius** [comment]
The jar is indeed build from the default branch, but the Cloud Spanner database I was trying to connect is not created with a PostgreSQL dialect.

Is there any way to use PGAdapter and connect it to a Cloud Spanner db that is not created with a PostgreSQL dialect?

**Comment by olavloite** [comment]
> Is there any way to use PGAdapter and connect it to a Cloud Spanner db that is not created with a PostgreSQL dialect?

Not really, at least not in a way that is supported, as some features in PGAdapter will also assume that the backend database uses the PostgreSQL dialect. It will for example in some cases automatically execute queries to get metadata about the tables in the database, and while doing so assume that the backend uses PostgreSQL style data types, schema names, etc. So you are probably best off by creating a separate fork of the project if that is what you really want to do.

The first place to look to work around the issue that you are currently running into would be here: https://github.com/GoogleCloudPlatform/pgadapter/blob/20754db9266f51af3b44fbb41137d12b1e551b3c/src/main/java/com/google/cloud/spanner/pgadapter/ProxyServer.java#L176

But the best bet is really to only use it for databases that have been created with the PostgreSQL dialect. Is there a specific reason that you want to use PGAdapter with a Cloud Spanner database that uses the GoogleSQL dialect? The reason that I'm asking is that there might be other drivers or tools around that could help for your specific use case.

**Comment by olavloite** [comment]
Closing as there is not much we can do about it in PGAdapter.
