### ISSUE TITLE
com.google.cloud.spanner.pgadapter.error.PGException: Invalid bootstrap message length: 1702390132

### ISSUE THREAD

**Issue by fengmao** [GoogleCloudPlatform/pgadapter#548]
i try to run pgadapter in google cloud run container, get `com.google.cloud.spanner.pgadapter.error.PGException: Invalid bootstrap message length: 1702390132` when connect with golang pgx v4.17.2

**Comment by olavloite** [comment]
@fengmao Thanks for reaching out to us. Would you mind giving a little more detail on exactly how you are running PGAdapter in this case?

You write that you try to run it in a Google Cloud Run Container. However, as I understand it, Google Cloud Run only supports containers that contain either web applications or batch processing. PGAdapter requires that it can be bound to a fixed TCP port, and will then listen for specific binary messages from a PostgreSQL client.

**Comment by olavloite** [comment]
@fengmao Friendly ping. Would it be possible to add a little more detail to this issue regarding how you were running PGAdapter when you saw this error?

**Comment by fengmao** [comment]
problem solved, close now
