### ISSUE TITLE
 Could not resolve dependencies

### ISSUE THREAD

**Issue by andrii-svystovych** [GoogleCloudPlatform/pgadapter#7]
Hi, 
I got an issue trying to build an application by running `mvn package -P shade`

`[ERROR] Failed to execute goal on project google-cloud-spanner-pgadapter: Could not resolve dependencies for project com.google.cloud:google-cloud-spanner-pgadapter:jar:0.1.0-pg-SNAPSHOT: Failed to collect dependencies at com.google.cloud:google-cloud-spanner-jdbc:jar:2.4.4-pg-SNAPSHOT: Failed to read artifact descriptor for com.google.cloud:google-cloud-spanner-jdbc:jar:2.4.4-pg-SNAPSHOT: Could not transfer artifact com.google.cloud:google-cloud-spanner-jdbc:pom:2.4.4-pg-SNAPSHOT from/to artifact-registry (artifactregistry://us-west1-maven.pkg.dev/span-cloud-testing/spangres-artifacts): Permission denied on remote repository (or it may not exist).`

**Comment by Vizerai** [comment]
Currently PGAdapter is in public preview, but there are Postgres specific dependencies that require being whitelisted to have access to.

Please fill out this form if you are interested in signing up for the public preview:
https://goo.gle/PostgreSQL-interface

**Comment by olavloite** [comment]
@andrii-svystovych The current code base no longer uses PostgreSQL specific dependencies, but only publicly available dependencies that can be downloaded from Maven Central. So it should now be possible to build PGAdapter locally.
