### ISSUE TITLE
Feature Request: Build release image using non-root user

### ISSUE THREAD

**Issue by joshbautista** [GoogleCloudPlatform/pgadapter#895]
### Feature Request
Modify the Dockerfile [that builds the release image](https://github.com/GoogleCloudPlatform/pgadapter/blob/80e9c8b988a168b30d44335b5de3c09e57c18d76/build/Dockerfile#L27-L40) to utilize a non-root user.

### Background
Use of pgadapter is being flagged by cloud security vulnerability scans due to the main process running as root. Running containers as a non-root user is also a [generally accepted security practice](https://www.tenable.com/audits/items/CIS_Docker_v1.3.1_L1_Docker_Linux.audit:bdcea17ac365110218526796ae3095b1).

### Possible Solutions

1. With the existing image (eclipse-temurin), utilize standard patterns to create a non-root user and use that non-root user as the executor.

1. Convert to [distroless images](https://github.com/GoogleContainerTools/distroless/blob/main/java/README.md), similarly to how [cloud-sql-proxy](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/d8fe2e9a14207c53f56b0faafc3038db8bf2508d/Dockerfile#L28-L33) is built.

**Comment by olavloite** [comment]
@joshbautista Thanks for the feature request, and sorry for not getting to you earlier. We'll look into it. Things that we need to take into account are:
1. The Docker container must for most use cases have access to the host file system to read the credentials file that is used to connect to Cloud Spanner.
2. We need to make sure we don't make any breaking changes to existing users.

(I'm not saying that any of the above needs to be a blocker for this, just that we need to look into it to get an understanding of what it would mean)

**Comment by joshbautista** [comment]
No problem, thanks for following up! I totally understand swapping to a non-root user is a non-trivial change and can cause havoc if done without care.
